### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by JeffSpies** [nfour/eslint-config-standard-typescript-prettier#1]
Would you consider licensing your code? Without it, I suspect a lot of people will be in a position where they [don't feel comfortable](https://choosealicense.com/no-permission/) using it.

Happy to help or submit a pull request, but, along with providing a [guide](https://choosealicense.com/) to make a decision, Github [makes it easy](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to add a license to your repo.

Thanks for considering it!

**Comment by nfour** [comment]
Hey @JeffSpies thanks for noticing. I've added `MIT` to the package.json, let me know if this is satisfactory.

**Comment by JeffSpies** [comment]
Thanks! That's good enough for my purposes, but the typical thing would be to also add a LICENSE file to the root of the repo. One benefit is that Github will use that file to generate metadata and show a license tag on the repo, which I've found useful.

**Comment by nfour** [comment]
@JeffSpies  ahh, thats how it does it. I though it also read the package.json as github tends to read it to map out dependencies anyway. Thanks for the tip!
